### ISSUE TITLE
Failed to upload images for a step in How-to

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#690]
**Describe the bug**
After creating, images of steps were either missing or lack of public access.
![broken-images](https://user-images.githubusercontent.com/2813016/66921639-d3529c80-f04f-11e9-8e85-0de0e33e5ecc.png)

![missing-images](https://user-images.githubusercontent.com/2813016/66921880-37756080-f050-11e9-96eb-45afefb0edb3.png)

**To Reproduce**
Refer to [**Create a How-to**] test case

**Expected behavior**
- Images should be shown correctly after a how-to is created. There should be no missing images.

**Comment by drydenwilliams** [comment]
This should be fixed as part of #691

**Comment by tmhung88** [comment]
@drydenwilliams it's not fixed. The upload functionality is broken for both create/edit a howto

**Comment by BenGamma** [comment]
Is this still to fix ?

**Comment by BenGamma** [comment]
Create a how-to test case works now. It's weird as I can't really point out which commit fixed this issue, but it's fixed !
